apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      name: {{ .Values.app.name }}-deployment
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        name: andersand
        env:
          - name: TITLE
            value: {{ .Values.app.title }}