apiVersion: v1
kind: ServiceAccount
metadata:
  name: demoserviceaccount
  namespace: tekno-demo-teacher-rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rbac-pod-reader
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-pod-reader-demoserviceaccount
  namespace: tekno-demo-teacher-rbac
subjects:
- kind: ServiceAccount
  name: demoserviceaccount
  namespace: tekno-demo-teacher-rbac
roleRef:
  kind: Role
  name: rbac-pod-reader
  apiGroup: rbac.authorization.k8s.io  