apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: {{ .Values.app.name }}pod
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}pod
    spec:
      containers:
      - image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        name: {{ .Values.app.name }}container
        env:
          - name: TITLE
            value: SuperUsers2024
    
    
