apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mongopod
  template:
    metadata:
      labels:
        app: mongopod
    spec:
      containers:
      - image: mongo
        name: mongocontainer
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: mongoUserName
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: mongoPassword
        volumeMounts:
          - mountPath: /data/db
            name: mongodb
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: ClusterIP
  selector:
    app: mongopod
  ports:
    - port: 27017
      targetPort: 27017