apiVersion: v1
kind: Namespace
metadata:
  name: ownapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ownapp
  namespace: ownapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ownapp
  template:
    metadata:
      labels:
        app: ownapp
    spec:
      containers:
      - name: myapp-container
        image: myown:1.0
        ports:
        - containerPort: 80
