apiVersion: v1
kind: Namespace
metadata:
  name: ownapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ownapp
  namespace: ownapp
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: ownapp
  template:
    metadata:
      labels:
        app: ownapp
    spec:
      containers:
      - name: myapp-container
        image: myown:1.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80


