apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-dynamic-demo-pvc
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 5Gi