apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: demofirst
  template:
    metadata:
      labels:
        app: demofirst
    spec:
      containers:
      - image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        name: aks-helloworld
        env: 
        - name: TITLE
          value: 'multinodes'
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: ClusterIP
  selector:
    app: demofirst
  ports:
    - port: 80
