apiVersion: apps/v1
kind: Deployment
metadata:
  name: delayedweather-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: delayedweather
  template:
    metadata:
      labels:
        app: delayedweather
    spec:
      containers:
        - image: teknoweather:0.2
          name: delayedweather-container
      initContainers:
        - image: sleeper:0.7
          name: slepper-container
          env:
            - name: x_delay
              value: '15000'
---
apiVersion: v1
kind: Service
metadata:
  name: delayedweather-service
spec:
  type: NodePort
  selector:
    app: delayedweather
  ports:
    - port: 80
      targetPort: 80