apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldapp2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworldapp2
  template:
    metadata:
      labels:
        app: helloworldapp2
    spec:
      containers:
        - image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
          name: helloworldapp2-container
          env:
            - name: TITLE
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: thetitle
---
apiVersion: v1
kind: Service
metadata:
  name: helloworldapp2-service
spec:
  type: NodePort
  selector:
    app: helloworldapp2
  ports:
    - port: 80
      targetPort: 80