apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldapp1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworldapp1
  template:
    metadata:
      labels:
        app: helloworldapp1
    spec:
      containers:
        - image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
          name: helloworldapp1-container
          env:
            - name: TITLE
              value: 'Application 1'
---
apiVersion: v1
kind: Service
metadata:
  name: helloworldapp1-service
spec:
  type: NodePort
  selector:
    app: helloworldapp1
  ports:
    - port: 80
      targetPort: 80