apiVersion: batch/v1
kind: Job
metadata:
  name: sleeper-job
spec:
  template:
    spec:
      containers:
        - image: sleeper:0.7
          name: sleep-container
          env:
            - name: x_delay
              value: '20000'
            - name: x_url
              value: 'https://en34wxdioc8w7.x.pipedream.net/'
      restartPolicy: Never

