apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
        - image: sleeper:0.1
          name: sleep-container
          env:
            - name: x_delay
              value: '5000'
---
apiVersion: v1
kind: Service
metadata:
  name: sleep-service
spec:
  type: NodePort
  selector:
    app: sleep
  ports:
    - port: 80
      targetPort: 80