apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: hellopod
  template:
    metadata:
      labels:
        app: hellopod
    spec:
      containers:
      - image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        name: hellocontainer
        env:
          - name: TITLE2
            valueFrom:
              configMapKeyRef:
                  name: test-config
                  key: title
          - name: TITLE
            valueFrom:
              secretKeyRef:
                  name: secret-demo
                  key: thesecrettitle
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: ClusterIP
  selector:
    app: hellopod
  ports:
    - port: 80
      targetPort: 80