apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lyngdemo2
  name: mydeployment
  namespace: lyngdemo2
spec:
  replicas: 3
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: lyngdemo2
  template:
    metadata:
      labels:
        app: lyngdemo2
    spec:
      containers:
      - name: asyncapi
        image: iitaks.azurecr.io/asyncapi:2.0
        env:
        - name: version
          valueFrom:
            secretKeyRef:
              name: lyngdemo2-secret
              key: secret_version
        ports:
        - containerPort: 80