apiVersion: v1
kind: Namespace
metadata:
  name: asyncapi
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: asyncapi
  name: asyncapi-deployment
  namespace: asyncapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asyncapi
  template:
    metadata:
      labels:
        app: asyncapi
    spec:
      containers:
      - name: asyncapi
        image: iitaks.azurecr.io/asyncapi:1.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: asyncapi-service
  namespace asyncapi
spec:
  selector:
    app: asyncapi
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    