apiVersion: v1
kind: Namespace
metadata:
  name: debug
---
apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: debug
spec:
  containers:
  - name: pod
    image: alpine
    command:
    - "/bin/sh"
    - "-c" 
    - "apk add --no-cache curl bash && sleep 60m"