apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        name: {{ .Values.app.name }}pod
        env:
          - name: TITLE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.app.name }}-cm
                key: title