apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hello-deployment
spec:
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
        - name: helloappcontainer
          image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
          env:
            - name: TITLE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name