apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:    
      containers:
      - image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        name: helloworld