apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-{{ .Values.env }}-service
spec:
  selector:
    app: {{ .Values.app.name }}-{{ .Values.env }}
  ports:
    - name: main
      port: 80
      targetPort: 80
