apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.app.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /{{ .Values.app.name }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.app.name }}-service
            port:
              number: 80
