apiVersion: apps/v1
kind: Deployment
metadata:
  name: demofirst
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demofirst
  template:
    metadata:
      labels:
        app: demofirst-deployment
    spec:
      containers:
      - image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        name: aks-helloworld
        env: 
        - name: TITLE
          value: 'Welcome to the Kubernetes class'

