apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploymentms2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hellotestms2
  template:
    metadata:
      labels:
        app: hellotestms2
    spec:
      containers:
        - name: hello-containerms2
          image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
          volumeMounts:
            - name: config
              mountPath: "/tmp/mlc"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: ms2-configmap
             
---
apiVersion: v1
kind: Service
metadata:
  name: test-servicems2
spec:
  selector:
    app: hellotestms2
  ports:
    - port: 80
      targetPort: 80