apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      volumes:
        - name: shared-html
          emptyDir: {}
      containers:
        - name: maincontainer
          image: nginx
          volumeMounts:
            - name: shared-html
              mountPath: /usr/share/nginx/html
      initContainers:
        - name: helpercontainer
          image: busybox:1.28
          volumeMounts:
            - name: shared-html
              mountPath: /html
          command: ['sh', '-c']
          args: 
            - echo '<h1>hello</h1>' > /html/index.html;
              sleep 5;
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: 80
      targetPort: 80
