apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: hellopod
  template:
    metadata:
      labels:
        app: hellopod
    spec:
      containers:
      - image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        name: hellocontainer
        env:
          - name: TITLE
            value: SuperUsers2024
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
            
    
    
