apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myfirstapplication
  name: mydeployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: myfirstapplication
  template:
    metadata:
      labels:
        app: myfirstapplication
      name: myfirstpod
    spec:
      containers:
      - image: iitaks.azurecr.io/asyncapi:1.2
        name: mycontainer
        env:
        - name: TITLE
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: thetitle
       