apiVersion: apps/v1
kind: Deployment
metadata:
  name: forca2024-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: forca2024
  template:
    metadata:
      labels:
        app: forca2024
    spec:
      containers:
      - name: helloworld-container
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
