apiVersion: apps/v1
kind: Deployment
metadata:
  name: mortenstest-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mortentest
  template:
    metadata:
      labels:
        app: mortentest
    spec: ## POD
      containers:
      - image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        name: myhelloworldpodtest