apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.app.name }}-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}app
  template:
    metadata:
      name: {{ .Values.app.name }}pod
      labels:
        app: {{ .Values.app.name }}app
    spec:
      containers:
        - name: {{ .Values.app.name }}pod
          image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
          env:
            - name: TITLE
              value: {{ .Values.app.name }}