apiVersion: v1
kind: Namespace
metadata:
  name: ...
---
apiVersion: v1
kind: Pod
metadata: 
  labels:
    app: asyncapi
  name: asyncapi-pod
  namespace: ...
spec:
  containers:
  - name: asyncapi
    image: iitaks.azurecr.io/asyncapi:1.2
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: asyncapi-service
  namespace: ...
spec:
  selector:
    app: asyncapi
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    