apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-02-27T07:34:03Z"
  labels:
    run: app1
  name: app1
  namespace: app1
  resourceVersion: "2516"
  uid: 2596d2ad-4802-45c2-8db1-d7ac7016a7d7
spec:
  containers:
  - image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
    imagePullPolicy: IfNotPresent
    name: app1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-75mq5
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: the2cluster-worker
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-75mq5
    secret:
      defaultMode: 420
      secretName: default-token-75mq5
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-02-27T07:34:03Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-02-27T07:34:03Z"
    message: 'containers with unready status: [app1]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-02-27T07:34:03Z"
    message: 'containers with unready status: [app1]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-02-27T07:34:03Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
    imageID: ""
    lastState: {}
    name: app1
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: ContainerCreating
  hostIP: 172.18.0.3
  phase: Pending
  qosClass: BestEffort
  startTime: "2023-02-27T07:34:03Z"