apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicon-deployment
  namespace: multicon
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multicon
  template: ## Pod
    metadata:
      name: multicon-pod
      labels:
        app: multicon
    spec:
      containers:
      - name: con1
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
          hostPort: 80
        env:
        - name: TITLE
          value: 'Container 1'
      - name: con2
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 81
          hostPort: 81
        env:
        - name: TITLE
          value: 'Container 2' 