apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: helloworld-daemon
spec:
  selector:
    matchLabels:
      name: abc
  template:
    metadata:
      labels:
        name: abc
    spec:
      containers:
      - name: hellodaemon
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1