
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volumedemo-pvc-2
  namespace: volumedemo
  labels:
    app: volumedemo-2
spec:
  volumeName: volumedemo-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # The amount of the volume's storage to request
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volumedemo-deployment-2
  namespace: volumedemo
  labels:
    app: volumedemo-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volumedemo-2
  template:
    metadata:
      labels:
        app: volumedemo-2
    spec:
      containers:
      - name: nginxcontainer
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: mydir
      volumes:
      - name: mydir
        persistentVolumeClaim:
          claimName: volumedemo-pvc-2
---
apiVersion: v1
kind: Service
metadata: 
  name: volumedemo-service-2
  namespace: volumedemo
spec:
  selector:
    app: volumedemo-2
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80