apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    command: ["/bin/sh", "-c"]
    args:
      - apt-get update && apt-get install -y curl && apt-get install -y vim; sleep 3600

