apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
spec:
  replicas: 4
  selector:
    matchLabels:
      bent: forcaapp1
  template:
    metadata:
      name: forcapod7
      labels:
        bent: forcaapp1
    spec:
      containers:
      - image: nginx
        name: andersand
---
apiVersion: v1
kind: Service
metadata:
  name: deployment1-service
spec:
  type: ClusterIP
  selector:
    bent: forcaapp1
  ports:
  - port: 80
    targetPort: 80    
