apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
spec:
  replicas: 10
  selector:
    matchLabels:
      bent: forcaapp1
  template:
    metadata:
      name: forcapod7
      labels:
        bent: forcaapp1
    spec:
      containers:
      - image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        name: andersand
        env:
          - name: TITLE
            valueFrom:
              configMapKeyRef:
                name: myconfigmap
                key: webtitle
---
apiVersion: v1
kind: Service
metadata:
  name: deployment1-service
spec:
  type: ClusterIP
  selector:
    bent: forcaapp1
  ports:
  - port: 80
    targetPort: 80    
