apiVersion: apps/v1
kind: Deployment
metadata:
  name: volumedemo1-deployment
  namespace: volumedemo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volumedemo1
  template:
    metadata:
      labels:
        app: volumedemo1
    spec:
      containers:
      - name: nginxcontainer
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: mydir
      volumes:
      - name: mydir
        persistentVolumeClaim:
          claimName: volumedemo1-pvc
  