apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volumedemo1-pvc
  namespace: volumedemo1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi